### ISSUE TITLE
dbt-hive can only connect to default database

### ISSUE THREAD

**Issue by hyewonee-0** [cloudera/dbt-hive#73]
Hi,

I am trying to connect database specified in profiles.yml.
but it seems dbt-hive that connecting default database, not using `schema` property.
      
Is there a way to connect specific database using dbt-hive?

**Comment by tovganesh** [comment]
You should be able to use a custom schema as follows:
<pre>
dbt_hive_demo:
  outputs:
    dev_cia_cdp:
      auth_type: ldap
      host: hostname
      http_path: path
      password: pwd
      port: 443
      schema: my_custom_schema
      threads: n
      type: hive
      use_http_transport: true
      use_ssl: true
      username: name
  target: dev_cia_cdp
  </pre>

**Comment by hyewonee-0** [comment]
Hello @tovganesh , I added custom schema but it does not working.

And I think dbt-hive does not using custom schema property when connecting.
https://github.com/cloudera/dbt-hive/blob/47bbb1447afa86621799cf7056314ac534cea441/dbt/adapters/hive/connections.py#L210-L218

I am using kerberos for auth mechanism and authenticated before running `dbt debug`.

Here's the profiles.yml I am using.

```yaml
dbt_dev:
  outputs:
    dev:
      type: hive
      schema: schema_name
      host: hostname
      port: port
      auth_type: KERBEROS
      kerberos_service_name: hive
      username: username
      use_ssl: False
      use_http_transport: False

  target: dev

```

Am I missing something? or Do I have to add other properties to connect hive?
Thanks for helping.
